In [1]:
import this 

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [17]:
ls

 Volume in drive C is Windows-SSD
 Volume Serial Number is ACC4-1116

 Directory of C:\Users\faith

29/03/2025  11:51    <DIR>          .
25/01/2025  07:27    <DIR>          ..
03/10/2023  11:14    <DIR>          .anaconda
29/03/2025  11:28               495 .bash_history
22/02/2024  12:23    <DIR>          .conda
03/10/2023  11:14                25 .condarc
03/10/2023  11:14    <DIR>          .continuum
18/03/2025  19:31               186 .gitconfig
29/03/2025  10:59    <DIR>          .ipynb_checkpoints
28/02/2024  21:41    <DIR>          .ipython
01/10/2024  09:56    <DIR>          .julia
18/02/2025  18:46    <DIR>          .jupyter
03/11/2024  07:57    <DIR>          .matplotlib
05/12/2023  21:17    <DIR>          .ms-ad
17/02/2025  08:43    <DIR>          .vscode
05/11/2024  17:21           101,288 AE HW1 group19 Slobodnìk Mashiba Mothalakottam.ipynb
18/12/2024  19:58           220,985 AE HW3 group19 Slobodnìk Mashiba Mothalakottam.ipynb
03/10/2023  11:13    <DIR>          anacon

In [10]:
print("hello, world")

hello, world


In [18]:
x=1


In [19]:
x

1

In [20]:
'2'

'2'

In [21]:
print('hello, world')

hello, world


In [22]:
print("Hello, World!")

Hello, World!


In [23]:
o1 = 'Hello world'

In [24]:
o1 + o1

'Hello worldHello world'

In [25]:
type

type

In [26]:
type(print)

builtin_function_or_method

In [27]:
o2 + o2

NameError: name 'o2' is not defined

In [28]:
type(o1)

str

In [29]:
o2 = 3

In [30]:
type(o2)

int

In [31]:
print(type(o2))

<class 'int'>


In [33]:
class person: 
    name = 'chiluba'
    age = 29

In [34]:
person.name

'chiluba'

In [37]:
person.age

29

In [38]:
person = person()

In [39]:
print(person.name)

chiluba


In [40]:
o1

'Hello world'

In [41]:
type(o1)

str

In [42]:
o1 = o1.replace('Hello', 'Hi')

In [43]:
o1

'Hi world'

In [44]:
o1 = o1.replace('Hi', 'Hello Miss Chichi')

In [45]:
o1

'Hello Miss Chichi world'

In [46]:
o1 = o1.replace('Hello Miss Chichi', 'Hi')

In [47]:
o1

'Hi world'

In [48]:
dir(o1)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'stri

In [49]:
help(dir)

Help on built-in function dir in module builtins:

dir(...)
    dir([object]) -> list of strings
    
    If called without an argument, return the names in the current scope.
    Else, return an alphabetized list of names comprising (some of) the attributes
    of the given object, and of attributes reachable from it.
    If the object supplies a method named __dir__, it will be used; otherwise
    the default dir() logic is used and returns:
      for a module object: the module's attributes.
      for a class object:  its attributes, and recursively the attributes
        of its bases.
      for any other object: its attributes, its class's attributes, and
        recursively the attributes of its class's base classes.



In [50]:
dir()

['In',
 'Out',
 '_',
 '_19',
 '_20',
 '_24',
 '_25',
 '_26',
 '_28',
 '_30',
 '_34',
 '_37',
 '_40',
 '_41',
 '_43',
 '_45',
 '_47',
 '_48',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_exit_code',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i23',
 '_i24',
 '_i25',
 '_i26',
 '_i27',
 '_i28',
 '_i29',
 '_i3',
 '_i30',
 '_i31',
 '_i32',
 '_i33',
 '_i34',
 '_i35',
 '_i36',
 '_i37',
 '_i38',
 '_i39',
 '_i4',
 '_i40',
 '_i41',
 '_i42',
 '_i43',
 '_i44',
 '_i45',
 '_i46',
 '_i47',
 '_i48',
 '_i49',
 '_i5',
 '_i50',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'exit',
 'get_ipython',
 'o1',
 'o2',
 'open',
 'person',
 'quit',
 'this',
 'x']

In [52]:
type(print)

builtin_function_or_method

In [71]:
def my_function():
    print ("Hello, world!")

In [74]:
my_function()

Hello, world!


In [61]:
def add_to_num(orig_number, how_much_to_add):
    return orig_number + how_much_to_add

In [63]:
add_to_num(orig_number = "good", how_much_to_add = "202")

'good202'

In [64]:
add_to_num(20,20)

40

In [65]:
o7 = None
type(o7)

NoneType

In [67]:
type(print())

NoneType

In [68]:
print()

In [75]:
def hi(x):
    print(x)
    return 3


In [76]:
hi(1)

1


3

In [77]:
y = hi

In [78]:
y(1)

1


3

In [79]:
y

<function __main__.hi(x)>

In [80]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [83]:
for c in range(5):
    print(c)

0
1
2
3
4


In [89]:
if 1900 < year < 2100 and 1 <= month <= 12 \
   and 1 <= day <= 31 and 0 <= hour < 24 \
   and 0 <= minute < 60 and 0 <= second < 60:
   pass


NameError: name 'year' is not defined

In [87]:
month_names = ['January', 'February', 'March',
               'April', 'May', 'June']


In [91]:
import keyword
print(f"{keyword.kwlist} \n\n {dir(__builtins__)}")

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield'] 

 ['ArithmeticError', 'AssertionError', 'AttributeError', 'BaseException', 'BaseExceptionGroup', 'BlockingIOError', 'BrokenPipeError', 'BufferError', 'BytesWarning', 'ChildProcessError', 'ConnectionAbortedError', 'ConnectionError', 'ConnectionRefusedError', 'ConnectionResetError', 'DeprecationWarning', 'EOFError', 'Ellipsis', 'EncodingWarning', 'EnvironmentError', 'Exception', 'ExceptionGroup', 'False', 'FileExistsError', 'FileNotFoundError', 'FloatingPointError', 'FutureWarning', 'GeneratorExit', 'IOError', 'ImportError', 'ImportWarning', 'IndentationError', 'IndexError', 'InterruptedError', 'IsADirectoryError', 'KeyError', 'KeyboardInterrupt', 'LookupError', 'MemoryError', 'ModuleNotFoundErro

In [92]:
yield = 4

SyntaxError: assignment to yield expression not possible (141192470.py, line 1)

In [93]:
def my_gen():
    yield 1
    yield 2
    yield 3

gen = my_gen()
print(next(gen))  # Output: 1


1


In [94]:
3//2

1

In [95]:
3/2

1.5

In [96]:
3**2

9

In [97]:
3*2

6

In [98]:
3%

SyntaxError: invalid syntax (1825578211.py, line 1)

In [102]:
b = True
print(not b - 1)

True


In [114]:
integer_num = 4
print('Integer: ', integer_num, type(integer_num))

float_num = 4.
print('Float: ',float_num,type(float_num))

print(integer_num == float_num)

Integer:  4 <class 'int'>
Float:  4.0 <class 'float'>
True


In [115]:
if 0:
    print('ok')
elif True:
    print('also ok')
elif False:
    print('not ok')
else:
    print('final else')

also ok


In [116]:
l1 = [1,2,3,4,5]
l2 = ['Hello', 'world']
l3 = ['combination', 2 , 'data types']
l4 = [print,list]

In [117]:
l1

[1, 2, 3, 4, 5]

In [118]:
[[i,i] for i in l1]

[[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]]

In [119]:
[[i,j] for i in range(4) for j in range(4)]

[[0, 0],
 [0, 1],
 [0, 2],
 [0, 3],
 [1, 0],
 [1, 1],
 [1, 2],
 [1, 3],
 [2, 0],
 [2, 1],
 [2, 2],
 [2, 3],
 [3, 0],
 [3, 1],
 [3, 2],
 [3, 3]]

In [120]:
numbers = [10, 20, 30, 40, 50]
iter_obj = iter(numbers)
print(next(iter_obj))

10


In [121]:
print(next(iter_obj))

20


In [122]:
print("hi" + str(1))
print(f"hi {1}")

hi1
hi 1


In [123]:
txt_var = 'my name is chiluba'

In [125]:
print(f"my name is chiluba")
print(f"i am also single")

my name is chiluba
i am also single


In [126]:
'   Chiluba is beautiful   ' .strip()

'Chiluba is beautiful'

In [129]:
'   Chiluba is beautiful   ' .replace("", "*")

'* * * *C*h*i*l*u*b*a* *i*s* *b*e*a*u*t*i*f*u*l* * * *'

In [133]:
a = chr(128521)

In [131]:
print(a)

😉


In [141]:
colors = ['red', 'blue', 'green', 'black', 'white']
print(type(colors))

<class 'list'>


In [140]:
colors = ['red', 'blue', 'green', 'black', 'white']
print(type(colors))

<class 'list'>


In [144]:
tmp = list('abcde')
print(f"{colors} - {tmp}")

['red', 'blue', 'green', 'black', 'white'] - ['a', 'b', 'c', 'd', 'e']


In [152]:
l = [1,2,3,4,5]
new_l = []
for el in l:
    new_l.append(el**2)
new_l

[1, 4, 9, 16, 25]

In [154]:
[el**2 for el in l]

[1, 4, 9, 16, 25]

In [156]:
l = ['a','b','c','d','e']

In [157]:
tmp

['a', 'b', 'c', 'd', 'e']

In [158]:
len(tmp)

5

In [159]:
tmp[12]

IndexError: list index out of range

In [160]:
tmp[-2]

'd'

In [161]:
colors

['red', 'blue', 'green', 'black', 'white']

In [162]:
print(colors[1])

blue


In [164]:
print(colors[4])

white


In [165]:
for col in colors:
    print(col)

red
blue
green
black
white


In [168]:
print(colors[2:])

['green', 'black', 'white']


In [169]:
print(colors[:-1])

['red', 'blue', 'green', 'black']


In [171]:
colors[-1:]

['white']

In [172]:
colors[::2]

['red', 'green', 'white']

In [173]:
empty_dict = {}
tel = {'chiluba': 29, 'mashiba': 25}
print(tel)

{'chiluba': 29, 'mashiba': 25}


In [174]:
tel['faith'] = 2
print(tel)

{'chiluba': 29, 'mashiba': 25, 'faith': 2}


In [178]:
print(tel['chiluba'])

29


In [179]:
tel['mashiba'] = 5915

In [180]:
print(tel)

{'chiluba': 29, 'mashiba': 5915, 'faith': 2}


In [181]:
'faith' in tel

True

In [182]:
a = (1,2,3)
b = a + (4,5,6)
print(b)

(1, 2, 3, 4, 5, 6)


In [183]:
c = b[1:]

In [184]:
print(c)

(2, 3, 4, 5, 6)


In [185]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [186]:
print(list('abcd'))
dir(list('abcd'))

['a', 'b', 'c', 'd']


['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [189]:
# lamda function

In [196]:
x = [1, 2, 3, 4, 5]
doubled = list(map(lambda x: x * 2, x))
print(doubled)


[2, 4, 6, 8, 10]


In [197]:
# Intergers
# Float
# Strings
# Bolean

In [198]:
[1, 'a', 3.14, True]

[1, 'a', 3.14, True]

In [199]:
# !pip freeze

In [200]:
!pip freeze | grey numpy # bit of bash magic

'grey' is not recognized as an internal or external command,
operable program or batch file.


In [201]:
!pip freeze | grep numpy # bit of bash magic

'grep' is not recognized as an internal or external command,
operable program or batch file.


In [202]:
!pip freeze > requirements.tx

In [203]:
# executing shell commands from jupiter notebook
# !ls -lha
# !pip install numpy

In [204]:
!pip install numpy

In [205]:
import numpy as np

In [219]:
a = np.array([0,1,2,3,4,5])
print(a)

[0 1 2 3 4 5]


In [207]:
type(a)

numpy.ndarray

In [208]:
a.append(a)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [220]:
for i in a: 
    print(i)

0
1
2
3
4
5


In [214]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [221]:
# a._dir_()

In [222]:
a

array([0, 1, 2, 3, 4, 5])

In [223]:
print(a.ndim)
len(a)

1


6

In [224]:
print(a)

[0 1 2 3 4 5]


In [225]:
a.shape #

(6,)

In [228]:
print(type(a))

<class 'numpy.ndarray'>


In [229]:
b = a + 2

In [231]:
print(b)

[2 3 4 5 6 7]


In [233]:
a = np.array([1,2,3,4,5,6])
reshaped_a = a.reshape(2, 3)
print(reshaped_a)

[[1 2 3]
 [4 5 6]]


In [239]:
print(a[1:4])
print(a[::2])

[2 3 4]
[1 3 5]


In [242]:
a = np.append(a, 5)
print(a)

[1 2 3 4 5 6 5 5]


In [244]:
a = np.array(1,2,3,4,5)
b =  a * 2
print(b)

TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [245]:
b = a * 2
print(b)

[ 2  4  6  8 10 12 10 10]


In [247]:
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [248]:
np.array(matrix[0, 1])

array(2)

In [249]:
np?

In [254]:
import pandas as pd

# Load the CSV file into a pandas DataFrame
df = pd.read_csv('people.csv')

# Display the first few rows to verify the data
df.head()


FileNotFoundError: [Errno 2] No such file or directory: 'people.csv'

In [259]:
ls

 Volume in drive C is Windows-SSD
 Volume Serial Number is ACC4-1116

 Directory of C:\Users\faith

31/03/2025  13:33    <DIR>          .
25/01/2025  08:27    <DIR>          ..
03/10/2023  12:14    <DIR>          .anaconda
29/03/2025  12:28               495 .bash_history
22/02/2024  13:23    <DIR>          .conda
03/10/2023  12:14                25 .condarc
03/10/2023  12:14    <DIR>          .continuum
18/03/2025  20:31               186 .gitconfig
29/03/2025  11:59    <DIR>          .ipynb_checkpoints
28/02/2024  22:41    <DIR>          .ipython
01/10/2024  10:56    <DIR>          .julia
18/02/2025  19:46    <DIR>          .jupyter
03/11/2024  08:57    <DIR>          .matplotlib
05/12/2023  22:17    <DIR>          .ms-ad
17/02/2025  09:43    <DIR>          .vscode
05/11/2024  18:21           101,288 AE HW1 group19 Slobodnìk Mashiba Mothalakottam.ipynb
18/12/2024  20:58           220,985 AE HW3 group19 Slobodnìk Mashiba Mothalakottam.ipynb
03/10/2023  12:13    <DIR>          anacon

In [260]:
import os
print(os.getcwd())  # Get the current working directory


C:\Users\faith


In [261]:
import pandas as pd

# Use the raw URL from GitHub
url = "https://raw.githubusercontent.com/iesfsv/Data-Processing-in-Python/refs/heads/main/02_week/people.csv"

# Load the CSV file into a pandas DataFrame
df = pd.read_csv(url)

# Display the first few rows of the DataFrame
print(df.head())


    Name  Age
0  Alice   30
1    Bob   28


In [262]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [263]:
url = "https://raw.githubusercontent.com/iesfsv/Data-Processing-in-Python/refs/heads/main/05_week/data/train.csv"
df = pd.read_csv(url)
print(df.head())


   Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD   

In [270]:
path = "C:\\Users\\faith\\Downloads\\covid.zip"
with zipfile.ZipFile(path, 'r') as zip_ref:
    # List the files in the zip to find the CSV inside
    zip_ref.printdir()

# Display the first few rows of the dataframe
print(df.head())

File Name                                             Modified             Size
Covid data/CovidDeaths.csv                     2022-09-30 05:22:08     25898901
Covid data/CovidVaccinations.csv               2022-09-30 05:22:10     37691188
   Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0  